version: '3.9'

services:
  php:
    build: .
    image: omc-php
    container_name: omc-php
    expose:
      - "9000"
    volumes:
      - ./app:/var/www
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:stable
    container_name: omc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: omc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tempsensors
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2
    container_name: omc-redis

  worker:
    build: .
    image: omc-worker
    working_dir: /var/www
    volumes:
      - ./worker:/var/www
    depends_on:
      - redis
      - postgres
    scale: 4
    deploy:
      replicas: 4

volumes:
  pgdata:
